config/routes.rb
Languagecheck::Application.routes.draw do
  devise_for :users
  resources :users
  
  resources :languages do
    resources :questions, except: [:index] do 
      resources :answers
      post '/up-vote' => 'votes#up_vote', as: :up_vote
     post '/down-vote' => 'votes#down_vote', as: :down_vote
    end
   end

  resources :questions, only: [:index, :new, :create]
  #resources :comments
  
  get 'about' => 'welcome#about'
  root to: 'welcome#index' 
  end

app/models/question.rb
class Question < ActiveRecord::Base
  require 'obscenity/active_model'
  has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :answers, :reject_if => :all_blank, :allow_destroy=>true
  belongs_to :user
  belongs_to :language

  default_scope { order('created_at DESC') }
  
  validates :body, obscenity: true
  validates :body, length: { minimum: 10, maximum: 160 }, presence: true
  #validates :user, presence: true

  def unanswered
    answers.blank?
  end

  def answered
    answers.any?
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_language, except: [:index, :new]
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  def index
    @questions = current_user.questions
    @unanswered_questions = @questions.select(&:unanswered)
    @answered_questions = @questions.select(&:answered)

    @answers = current_user.answers
    @questions_i_answered = @answers.collect(&:question).uniq || []
    @answers_voted_up = @answers.voted_up || []
  end

  def show
    @question = Question.find(params[:id])
    @answer = Answer.new
  end

  def new
    @question = Question.new
    authorize @question
  end

  def edit
    @question = Question.find(params[:id])
    authorize @question
  end

  def update
     @question = Question.find(params[:id])
     authorize @question
     
     if @question.update_attributes(question_params)
       flash[:notice] = "Question was updated."
       redirect_to [@language, @question]
     else
       flash[:error] = "There was an error saving the question. Please try again."
       render :edit
     end
  end

  def create
     @question = Question.new(question_params)
     @question.language = @language
     @question.user = current_user
     authorize @question

     if @question.save
       flash[:notice] = "Question was saved."
       redirect_to [@language, @question]
     else
       flash[:error] = "There was an error saving the question. Please try again."
       Rails.logger.info ">>>>>>>> Question: #{@question.inspect}"
       Rails.logger.info ">>>>>>> Valid? #{@question.valid?}"
       Rails.logger.info ">>>> Errors: #{@question.errors.inspect}"
       render :new
     end
   end

  def destroy
    @question.destroy.find(params[:id])
    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end

  private

    def set_question
      @question = Question.find(params[:id])
    end

    def question_params
      params.require(:question).permit(:id, :body)

    end
   
    def set_language
      @language = Language.find(params[:language_id])
    end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_answer_fields.erb
<div class="nested-fields">
</div>

app/views/questions/_form.html.erb
<%= form_for [language, question] do |f| %>
<div class="form-group">
    <%= f.label :body %>
    <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter question here" %>
</div>
<div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
</div>
<% end %>

app/views/questions/_question.html.erb
<div class="media">
    <div class="media-body">
        <h4 class="media-heading">
        <%= question.language ? link_to(question.body, [question.language, question]) : question.body %>
        </h4>
        <small>
        submitted <%= time_ago_in_words(question.created_at) %> ago by <%= question.user.name %> <br/>
        <%= pluralize(question.answers.count, 'answer') %>
        </small>
    </div>
</div>

app/views/questions/edit.html.erb
<div class="wrapper">
  <h1>Edit Question</h1>
  <div class="row">
    <div class="col-md-4">
      <p>Guidelines for Questions</p>
      <ul>
        <li>160 character limit per question.</li>
        <li>Use your keyboard to make character symbols.</li>
      </ul>
    </div>
    <div class="col-md-8">
      <%= form_for [@language, @question] do |f| %>
      <% if @question.errors.any? %>
      <div class="alert alert-danger">
        <h4>There are <%= pluralize(@question.errors.count, "error") %>.</h4>
        <ul>
          <% @question.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
      <% end %>
      <%= form_group_tag(@question.errors[:body]) do %>
      <%= f.label :body %>
      <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter question here" %>
      <% end %>
      <div class="form-group">
        <%= f.submit "Save", class: 'btn btn-success' %>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/questions/index.html.erb
<div class="wrapper">
  <div class="row">
    <div class="col-md-8">
      <%= link_to "Ask a New Question", new_question_path, class: 'btn btn-success' %>
      <div>
        <h3>My Answered Questions</h3>
        <% if @answered_questions.blank? %>
        <small>You don't have any answers yet.</small>
        <% end %>
        <%= render @answered_questions %>
      </div>
      <div>
        <h3>My Unanswered Questions</h3>
        <% if @unanswered_questions.blank? %>
        <small>You don't have any unanswered questions.</small>
        <% end %>
        <%= render @unanswered_questions %>
      </div>
      <div>
        <h3>Questions I Answered</h3>
        <% if @questions_i_answered.blank? %>
        <small>You haven't answered any questions yet</small>
        <% end %>
        <%= render @questions_i_answered %>
      </div>
    </div>
  </div>
</div>

app/views/questions/new.html.erb
<div class="wrapper">
  <% if @question.errors.any? %>
  <div class="alert alert-danger">
    <h4>Please fix <%= pluralize(@question.errors.count, "error") %>.</h4>
    <ul>
      <% @question.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <h1>New Question</h1>
  <div class="row">
    <div class="col-md-4">
      <p>Question Guidelines</p>
      <ul>
        <li>160 character limit per question.</li>
        <li>Use your keyboard to make character symbols.</li>
      </ul>
    </div>
    <div class="col-md-8">
      <%= form_for [@language, @question] do |f| %>
      <div class="form-group">
        <br>
        <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter question here" %>
        <% unless @language %>
        <label>Select a language to ask a question</label>
        <%= select_tag "language_id", options_from_collection_for_select(Language.all, "id", "name") %>
        <% end %>
        <label>or add a new language:</label>
        <span id="new"><%= link_to "New Language", new_language_path %><span>
        </div>
        <div class="form-group">
          <%= f.submit "Submit Question", class: 'btn btn-success' %>
        </div>
        <% end %>
      </div>
    </div>
  </div>

app/views/questions/show.html.erb
<div class="wrapper">
  <h3>Question</h3>
  <div class="row">
    <div class="col-md-8">
      <p><%= @question.body %></p>
      <small>
      <%= image_tag(@question.user.avatar.tiny.url) if @question.user.avatar? %>
      submitted <%= time_ago_in_words(@question.created_at) %> ago by
      <%= @question.user.name %>
      </small>
      <div><% if policy(@question).edit? %>
        <%= link_to "Edit Question", edit_language_question_path(@language, @question), class: 'btn btn-success' %>
      <% end %></div>
    </div>
    <div class="col-md-4">
    </div>
  </div>
  <br/>
  <h3>Answers</h3>
  <% if @question.answers.blank? %>
        <small>No one has answered yet.</small>
        <% end %>

  <% @question.answers.each do |answer| %>

  <%= simple_format answer.body %>
  <small>
  <%= image_tag(answer.user.avatar.tiny.url) if answer.user.avatar? %>
  submitted <%= time_ago_in_words(answer.created_at) %> ago by
  <%= answer.user.name %>
  </small>
  <% end %>
  <br/>
  <% if policy(Answer.new).create? %>
  <h4 class="add-answer">Add an Answer</h4>
  <%= render "answers/form" %>
  <% end %>
</div>