config/routes.rb
Languagecheck::Application.routes.draw do
  devise_for :users
  resources :users
  
  resources :languages do
    resources :questions, except: [:index] do 
      resources :answers
      post '/up-vote' => 'votes#up_vote', as: :up_vote
     post '/down-vote' => 'votes#down_vote', as: :down_vote
    end
   end

  resources :questions, only: [:index, :new, :create]
  #resources :comments
  
  get 'about' => 'welcome#about'
  root to: 'welcome#index' 
  end

app/models/language.rb
class Language < ActiveRecord::Base
  require 'obscenity/active_model'
  has_many :questions

  default_scope { order('languages.name ASC') }

  validates :name, obscenity: true
  validates :name, length: { minimum: 3, maximum: 15 }, presence: true
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  before_action :set_language, only: [:show, :edit, :update, :destroy]

  def index
    @languages = Language.all
    authorize @languages
  end

  def show
    @language = Language.find(params[:id])
    @questions = @language.questions
    # authorize @language
  end

  def new
    @language = Language.new
    authorize @language
  end

  def edit
    @language = Language.find(params[:id])
    authorize @language
  end

  def create
     @language = Language.new(params.require(:language).permit(:name, :public))
     authorize @language
     if @language.save
       redirect_to @language, notice: "Language was saved successfully."

     else
       flash[:error] = "Error creating language. Please try again."
       render :new
     end
  end

  def update
     @language = Language.find(params[:id])
     authorize @language
     
     if @language.update_attributes(params.require(:language).permit(:name, :public))
       redirect_to @language
     else
       flash[:error] = "Error saving language. Please try again."
       render :edit
     end
  end

  def destroy
    @language.destroy
    respond_to do |format|
      format.html { redirect_to languages_url }
      format.json { head :no_content }
    end
  end

  private

    def set_language
      @language = Language.find(params[:id])
    end

    def language_params
      params.require(:language).permit(:name)
    end
end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/views/languages/_form.html.erb
<%= form_for(@language) do |f| %>
<% if @language.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@language.errors.count, "error") %> prohibited this language from being saved:</h2>
  <ul>
    <% @language.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div class="field">
  <%= f.label :name %><br>
  <%= f.text_field :name %>
</div>
<div class="actions">
  <%= f.submit %>
</div>
<% end %>

app/views/languages/edit.html.erb
<h1>Edit a Language</h1>
<div class="col-md-4">
    <%= form_for @language do |f| %>
    <div class="form-group">
        <% f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: "Enter language name here" %>
    </div>
    <%= f.submit "Save", class: 'btn btn-success' %>
    <% end %>
</div>
</div>

app/views/languages/index.html.erb
<div class="wrapper">
  <div class="row">
    <div class="col-md-8">
      <% if policy(Language.new).create? %>
      <%= link_to "Add a Language", new_language_path, class: 'btn btn-success' %>
      <% end %>
      <h3>Languages</h3>
      <hr class="star-primary" id="langstar">
      <% @languages.each do |language| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
          <%= link_to language.name, language %>
          </h4>
        </div>
      </div>
      <% end %>
    </div>
    <div class="col-md-4"
    </div>
  </div>
</div>

app/views/languages/new.html.erb
<div class="wrapper">
  <% if @language.errors.any? %>
  <div class="alert alert-danger">
    <h4>Please fix <%= pluralize(@language.errors.count, "error") %>.</h4>
    <ul>
      <% @language.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>
  <h1>Add a Language</h1>
  <div class="col-md-4">
    <%= form_for @language do |f| %>
    <div class="form-group">
      <% f.label :name %>
      <%= f.text_field :name, class: 'form-control', placeholder: "New language" %>
    </div>
    <%= f.submit "Add Language", class: 'btn btn-success add' %>
    <% end %>
  </div>
</div>
</div>

app/views/languages/show.html.erb
<div class="wrapper">
  <h1>Questions about <%= @language.name %></h1>
  <div>
    <% if policy(@language).create? %>
    <%= link_to "Ask a New Question", new_language_question_path(@language), class: 'btn btn-success question' %>
    <% end %>
  </div>
  <br/>
  <div class="row">
    <div class="col-md-8">
      <% @questions.each do |question| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
          <%= link_to question.body, [@language, question] %>
          </h4>
          <small>
          <%= image_tag(question.user.avatar.tiny.url) if question.user.avatar? %>
          submitted <%= time_ago_in_words(question.created_at) %> ago by
          <%= question.user.name %><br/>
          <%= pluralize(question.answers.count, 'answer') %>
          </small>
        </div>
      </div>
      <% end %>
    </div>
  </div>