config/routes.rb
Languagecheck::Application.routes.draw do
  devise_for :users
  resources :users
  
  resources :languages do
    resources :questions, except: [:index] do 
      resources :answers
      post '/up-vote' => 'votes#up_vote', as: :up_vote
     post '/down-vote' => 'votes#down_vote', as: :down_vote
    end
   end

  resources :questions, only: [:index, :new, :create]
  #resources :comments
  
  get 'about' => 'welcome#about'
  root to: 'welcome#index' 
  end

app/models/answer.rb
class Answer < ActiveRecord::Base
  require 'obscenity/active_model'
  belongs_to :question
  belongs_to :user
  has_many :votes, dependent: :destroy
  #has_many :comments, dependent: :destroy

  #after_create :send_answer_emails

  default_scope { order('rank DESC') } #rank by votes if votes are present, otherwise rank by DESC
  scope :voted_up, -> { joins(:votes).where("votes.value = ?", 1) } 

  validates :body, obscenity: true
  validates :body, length: { minimum: 1, maximum: 160 }, presence: true

  def up_votes
    votes.where(value: 1).count
  end

  def down_votes
    self.votes.where(value: -1).count
  end

  def points
    self.votes.sum(:value).to_i
  end

  def update_rank
     age = (created_at - Time.new(1970,1,1)) / (60 * 60 * 24) # 1 day in seconds
     new_rank = points + age
     update_attribute(:rank, new_rank)
  end
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  before_action :set_language_and_question
  before_action :set_answer, only: [:show, :edit, :update, :destroy]

  def index
    @answers = Answer.all
      authorize @answers
  end

  def show
  end

  def new
    @answer = Answer.new
        authorize @answer
  end

  def edit


  end

  def create
    @answer = Answer.new(answer_params)
    @answer.question = @question
    @answer.user = current_user
      authorize @answer

    respond_to do |format|
      if @answer.save
        format.html { redirect_to [@language, @question], notice: 'Answer was successfully created.' }
        format.json { render action: 'show', status: :created, location: @answer }
      else
        format.html { redirect_to [@language, @question], error: 'Answer was  not successfully created.' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @answer.update(answer_params)
        format.html { redirect_to @answer, notice: 'Answer was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @answer.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @answer.destroy
    respond_to do |format|
      format.html { redirect_to answers_url }
      format.json { head :no_content }
    end
  end

  private

    def set_answer
      @answer = Answer.find(params[:id])
      @answer ||= @question.answers.new
    end

     def answer_params
      params.require(:answer).permit(:id, :body)
    end

    def set_language_and_question
      @language = Language.find(params[:language_id])
      @question = Question.find(params[:question_id])
    end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/answers/_form.html.erb
<%= form_for [@language, @question, @answer] do |f| %>
<div class="field">
  <%= f.text_area :body %>
</div>
<div class="actions">
  <%= f.submit "Add Answer", class: "btn btn-success" %>
</div>
<% end %>
<% if @answer.errors.any? %>
<div id="error_explanation">
  <h2>Please fix<%= pluralize(@answer.errors.count, "error") %></h2>
  <ul>
    <% @answer.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/answers/_voter.html.erb
<% if policy( Vote.new ).create? %>
<div class="vote-arrows pull-left">
  <div>
    <%= link_to " ",
    post_up_vote_path(answer),
    class: "glyphicon glyphicon-chevron-up #{(current_user.voted(answer) && current_user.voted(answer).up_vote?) ? 'voted' : '' }", method: :post %>
  </div>
  <div>
    <strong><%= answer.points %></strong>
  </div>
  <div>
    <%= link_to " ",
    post_down_vote_path(answer),
    class: "glyphicon glyphicon-chevron-down #{(current_user.voted(answer) && current_user.voted(answer).down_vote?) ? 'voted' : '' }" , method: :post%>
  </div>
</div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing answer</h1>
<%= render 'form' %>
<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<h1>Listing answers</h1>
<table>
  <thead>
    <tr>
      <th>Body</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% if policy(Answer.new).create? %>
    <%= link_to "New Answer", new_answer_path, class: 'btn btn-success' %>
    <% end %>
    <% @answers.each do |answer| %>
    <tr>
      <td><%= answer.body %></td>
      <td><%= link_to 'Show', answer %></td>
      <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
      <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
    <% end %>
  </tbody>
</table>
<br>
<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New answer</h1>
<%= render 'form' %>
<%= link_to 'Back', :back %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>
<%= render "votes/voter" %>
<div>
    <h3>
    <%= pluralize(@answer.points, 'point') %>
    </h3>
    <small>
    <%= pluralize(@answer.up_votes, 'up vote') %>
    <%= pluralize(@answer.down_votes, 'down vote') %>
    </small>
</div>
<% if policy(Answer.new).create? %>
<p>
    <strong>Body:</strong>
    <%= @answer.body %>
</p>
<% end %>
<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>