config/routes.rb
Languagecheck::Application.routes.draw do
  devise_for :users
  resources :users
  
  resources :languages do
    resources :questions, except: [:index] do 
      resources :answers
      post '/up-vote' => 'votes#up_vote', as: :up_vote
     post '/down-vote' => 'votes#down_vote', as: :down_vote
    end
   end

  resources :questions, only: [:index, :new, :create]
  #resources :comments
  
  get 'about' => 'welcome#about'
  root to: 'welcome#index' 
  end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>LanguageCheck</title>
        <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
        <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
        <%= csrf_meta_tags %>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">
        <link href="http://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
        <link href="http://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css">
    </head>
    <!-- Navigation -->
    <nav class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand">
                <h2><%= link_to "LanguageCheck", root_path %></h2></a>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>
                    <!--                 <li class="page-scroll">
                        <a href="#portfolio"><li><%= link_to "About", about_path %></li></a>
                    </li> -->
                    <li class="page-scroll">
                        <a href="#about"><% if current_user %>
                            <li><%= link_to "My Questions", questions_path %></li>
                        <% end %></a>
                    </li>
                    <li class="page-scroll">
                    <li><%= link_to "Languages", languages_path %></a>
                </li>
                <div class="pull-right user-info">
                    <% if current_user %>
                    <%= link_to edit_user_registration_path do %>
                    &nbspAccount&nbsp&nbsp&nbsp
                    <% end %>
                    <%= link_to destroy_user_session_path, method: :delete do %>
                    Logout
                    <% end %>
                    <% else %>
                    <li><a id="sign">&nbsp<%= link_to "Sign In", new_user_session_path %>&nbsp&nbsp
                        <%= link_to "Sign Up", new_user_registration_path %>
                    <% end %></a></li>
                </div>
            </ul>
        </div>
    </div>
</nav>
<%= yield %>
</body>
</html>